### ISSUE TITLE
kakuyomu小説の変換時に発生する不具合

### ISSUE THREAD

**Issue by Am4hisa** [rogenobl/narou#4]
`narou web`を実行し小説の更新を行うとエラーが発生し処理が中断された。
リリースのp0.2(なろう用)およびv0.1(カクヨム用)を使用。
更新を試みた小説 https://kakuyomu.jp/works/1177354055311119303

cmdのログ
 ```
#<Thread:0x00000227387c0e00 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/web/web_worker.rb:46 run> terminated with exception (report_on_exception is true):
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/novelconverter.rb:202:in `txt_to_epub': invalid byte sequence in UTF-8 (ArgumentError)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/novelconverter.rb:315:in `convert_txt_to_ebook_file'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:300:in `convert_txt_to_ebook_file'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/commandbase.rb:152:in `call'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/commandbase.rb:152:in `hook_call'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:252:in `block in convert_novel_main'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:248:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:248:in `convert_novel_main'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:201:in `block (2 levels) in convert_novels'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/mixin/locker.rb:26:in `lock'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:200:in `block in convert_novels'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:199:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:199:in `with_index'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:199:in `convert_novels'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:159:in `block in main'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:152:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:152:in `main'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:133:in `execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/commandbase.rb:125:in `execute!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/commandbase.rb:134:in `execute!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:123:in `block in execute!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/narou.rb:369:in `concurrency_call'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/convert.rb:122:in `execute!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/update.rb:212:in `block in execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/update.rb:157:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/update.rb:157:in `each_with_index'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/command/update.rb:157:in `execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/commandbase.rb:125:in `execute!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/web/appserver.rb:575:in `block (2 levels) in <class:AppServer>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/web/web_worker.rb:47:in `block (3 levels) in start'
[2024-01-29 06:50:21] ERROR ArgumentError: invalid byte sequence in UTF-8\n\tC:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/narou-3.8.2/lib/novelconverter.rb:315:in `convert_txt_to_ebook_file'

```

GUIのログ
```
更新を開始します
ID:17　一生働きたくない俺が、クラスメイトの大人気アイドルに懐かれたら のあらすじが更新されています
ID:17　一生働きたくない俺が、クラスメイトの大人気アイドルに懐かれたら の変換を開始
縦書用の変換が終了しました
AozoraEpub3でEPUBに変換しています...更新を開始します
ID:17　一生働きたくない俺が、クラスメイトの大人気アイドルに懐かれたら のDL開始
第一章　腹ぺこアイドル編
1－1　腹ぺこアイドル (1/171) (新着)
1－2 (2/171) (新着)
1－3 (3/171) (新着)
2－1　お金＝パワー (4/171) (新着)
2－2 (5/171) (新着)
2－3 (6/171) (新着)
2－4 (7/171) (新着)
2－5 (8/171) (新着)
3－1　ミルフィーユスターズ (9/171) (新着)
3－2 (10/171) (新着)
3－3 (11/171) (新着)
4－1　夢の理由 (12/171) (新着)
4－2 (13/171) (新着)
4－3 (14/171) (新着)
5－1　引っ越しパーティー (15/171) (新着)
5－2 (16/171) (新着)
5－3 (17/171) (新着)
5－4 (18/171) (新着)
5－5 (19/171) (新着)
6－1　水族館デート (20/171) (新着)
6－2 (21/171) (新着)
6−3 (22/171) (新着)
6－4 (23/171) (新着)
7－1　悩む者たち (24/171) (新着)
7－2 (25/171) (新着)
7－3 (26/171) (新着)
7－4 (27/171) (新着)
7－5 (28/171) (新着)
8－1　その視線は (29/171) (新着)
8－2 (30/171) (新着)
8－3 (31/171) (新着)
8－4 (32/171) (新着)
8－5 (33/171) (新着)
8－6 (34/171) (新着)
9－　後日談くらいは平穏に (35/171) (新着)
第二章　夏休み編
10－1　終業式なのにプロローグ (36/171) (新着)
10－2 (37/171) (新着)
11－1　夏休みは波乱に満ちている。 (38/171) (新着)
11－2 (39/171) (新着)
11－3 (40/171) (新着)
11－4 (41/171) (新着)
12－1　一日彼氏 (42/171) (新着)
12－2 (43/171) (新着)
12－3 (44/171) (新着)
12－4 (45/171) (新着)
12－5 (46/171) (新着)
13－1　これが青春というのなら (47/171) (新着)
13－2 (48/171) (新着)
13－3 (49/171) (新着)
13－4 (50/171) (新着)
14－1　夏と言えば海という風潮 (51/171) (新着)
14－2 (52/171) (新着)
14－3 (53/171) (新着)
14－4 (54/171) (新着)
15－1　命令権 (55/171) (新着)
15－2 (56/171) (新着)
15－3 (57/171) (新着)
15－4 (58/171) (新着)
15－5 (59/171) (新着)
15－6 (60/171) (新着)
16－1　夏に置いてきた秘密 (61/171) (新着)
16－2 (62/171) (新着)
16－3 (63/171) (新着)
16－4 (64/171) (新着)
16－5 (65/171) (新着)
17－　告白 (66/171) (新着)
第三章　文化祭編
18－1　欲しくなる (67/171) (新着)
18－2 (68/171) (新着)
18－3 (69/171) (新着)
18－4 (70/171) (新着)
18－5 (71/171) (新着)
19－1　きっかけ (72/171) (新着)
19－2 (73/171) (新着)
19－3 (74/171) (新着)
19－4 (75/171) (新着)
19－5 (76/171) (新着)
19－6 (77/171) (新着)
20－1　新学期 (78/171) (新着)
20－2 (79/171) (新着)
20－3 (80/171) (新着)
20－4 (81/171) (新着)
20－5 (82/171) (新着)
21－1　文化祭準備 (83/171) (新着)
21－2 (84/171) (新着)
21－3 (85/171) (新着)
22－1　バンド (86/171) (新着)
22－2 (87/171) (新着)
22－3 (88/171) (新着)
22－4 (89/171) (新着)
23－1　本音 (90/171) (新着)
23－2 (91/171) (新着)
23－3 (92/171) (新着)
24－　前日 (93/171) (新着)
25－1　文化祭当日 (94/171) (新着)
25－2 (95/171) (新着)
25－3 (96/171) (新着)
25－4 (97/171) (新着)
25－5 (98/171) (新着)
25－6 (99/171) (新着)
25－7 (100/171) (新着)
26－1　後夜祭 (101/171) (新着)
26－2 (102/171) (新着)
26－3 (103/171) (新着)
26－4 (104/171) (新着)
26－5 (105/171) (新着)
27－　何があっても (106/171) (新着)
28－　再会 (107/171) (新着)
第四章
29－　楔 (108/171) (新着)
30－1　お断り (109/171) (新着)
30－2 (110/171) (新着)
30－3 (111/171) (新着)
30－4 (112/171) (新着)
30－5 (113/171) (新着)
30－6 (114/171) (新着)
31－1　対策会議 (115/171) (新着)
31－2 (116/171) (新着)
31－3 (117/171) (新着)
32－1　偽りの恋人 (118/171) (新着)
32－2 (119/171) (新着)
32－3 (120/171) (新着)
33－1　実家へのご挨拶？ (121/171) (新着)
33－2 (122/171) (新着)
33－3 (123/171) (新着)
33－4 (124/171) (新着)
33－5 (125/171) (新着)
34－1　思い出とさよなら (126/171) (新着)
34－2 (127/171) (新着)
34－3 (128/171) (新着)
35－1　親と子 (129/171) (新着)
35－2 (130/171) (新着)
35－3 (131/171) (新着)
36－1　終わりよければすべてよし？ (132/171) (新着)
36－2 (133/171) (新着)
36－3 (134/171) (新着)
36－4 (135/171) (新着)
37－　戒めを父に (136/171) (新着)
第五章
38－1　志藤凛太郎の朝 (137/171) (新着)
38－2 (138/171) (新着)
39－1　ハロウィンライブ (139/171) (新着)
39－2 (140/171) (新着)
39－3 (141/171) (新着)
40－1　ツインズ、襲来 (142/171) (新着)
40－2 (143/171) (新着)
40－3 (144/171) (新着)
40－4 (145/171) (新着)
41－１　好きこそ (146/171) (新着)
41－2 (147/171) (新着)
41－3 (148/171) (新着)
42－1　日々のご褒美 (149/171) (新着)
42－2 (150/171) (新着)
42－3 (151/171) (新着)
42－4 (152/171) (新着)
43－1　まるで家族のように (153/171) (新着)
43－2 (154/171) (新着)
43－3 (155/171) (新着)
44－1　敵情視察？ (156/171) (新着)
44－2 (157/171) (新着)
44－3 (158/171) (新着)
44－4 (159/171) (新着)
44－5 (160/171) (新着)
44－6 (161/171) (新着)
45－1　アカウント開設 (162/171) (新着)
45－2 (163/171) (新着)
45－3 (164/171) (新着)
46－1　志藤凛太郎の怒り (165/171) (新着)
46－2 (166/171) (新着)
46－3 (167/171) (新着)
46－4 (168/171) (新着)
46－5 (169/171) (新着)
47－1　独占権 (170/171) (新着)
47－2 (171/171) (新着)
ID:17　一生働きたくない俺が、クラスメイトの大人気アイドルに懐かれたら の変換を開始
縦書用の変換が終了しました
AozoraEpub3でEPUBに変換しています...
```

**Comment by Am4hisa** [comment]
既出でした。
https://github.com/whiteleaf7/narou/issues/399#issuecomment-1875320540
